dubbo:
  application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
    name: cart_consumer
  registry:                 #注册中心配置，用于配置连接注册中心相关信息。
    address: zookeeper://192.168.1.129:2181
  metadata-report:
    address: zookeeper://192.168.1.129:2181
  scan:
    base-packages: com.ft.gmall.cart.controller
  version: 1.0.0
  consumer:
    timeout: 600000
    check: false

server:
  port: 8073
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
