dubbo:
  application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
    name: manage_service
  registry:                 #注册中心配置，用于配置连接注册中心相关信息。
    address: zookeeper://192.168.1.129:2181
  metadata-report:
    address: zookeeper://192.168.1.129:2181
  protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
    name: dubbo
    port: 20888
  version: 1.0.0
  scan:
    base-packages: com.ft.gmall.manage.service #服务暴露与发现消费所在的package
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.129:3307/gmall_study?characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.1.129
    port: 6379
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
